name: tanggal_indonesia
description: A starting point for Dart libraries or applications.
version: 1.0.2
homepage: https://github.com/coimstark/tanggal_indonesia.dart.git
author: Coim Stark <coim@m-oga.id>

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
